binDir = path.join(os.projectdir(),"bin/Project 10-17")
includes("10 Camera")
includes("11 Blending")
includes("12 Depth and Stenciling")
includes("13 Living Without FX11")
includes("14 Depth Test")
includes("15 Geometry Shader Beginning")
includes("16 Stream Output")
includes("17 Tree Billboard")