if is_mode("debug") then
    binDir = path.join(os.projectdir(),"bin/Debug/Project 19-")
else 
    binDir = path.join(os.projectdir(),"bin/Release/Project 19-")
end
includes("Common")
includes("19 Meshes")
includes("20 Instancing and Frustum Culling")
includes("21 Picking")
includes("22 Static Cube Mapping")
includes("23 Dynamic Cube Mapping")
includes("24 Render To Texture")
includes("25 Normal Mapping")
includes("26 Compute Shader Beginning")
includes("27 Bitonic Sort")
includes("28 Waves")
includes("29 OIT")
includes("30 Blur and Sobel")
includes("31 Shadow Mapping")
includes("32 SSAO")
includes("33 Tessellation")
includes("34 Displacement Mapping")
includes("35 Particle System")
includes("36 Deferred Rendering")
includes("37 Tile-Based Deferred Rendering")
includes("38 Cascaded Shadow Mapping")
includes("39 VSM and ESM")
includes("40 FXAA")