target("Common")
    set_group(GroupName)
    set_kind("static")
    add_deps("ImGui")
    add_packages("assimp")
    add_headerfiles("**.h")
    add_files("**.cpp")
    add_includedirs("./",{public = true})
target_end()
